FROM golang:1.19-alpine

WORKDIR /app

COPY publisher.go .

RUN go mod init publisher
RUN go get github.com/gin-gonic/gin
RUN go get github.com/go-redis/redis/v8

RUN go build -o publisher .

CMD ["./publisher"]
