FROM golang:1.19-alpine

WORKDIR /app

COPY subscriber.go .

RUN go mod init subscriber
RUN go get github.com/gin-gonic/gin
RUN go get github.com/go-redis/redis/v8

RUN go build -o subscriber .

CMD ["./subscriber"]
